Add missing Tpl::TextEvent include.
This fixes this kind of error

  error: invalid use of incomplete type ‘class Tpl::TextEvent’
  In instantiation of ‘class QGlib::RefPointer<Tpl::TextEvent>’:

when trying to instantiate a message using the default constructor.